### ISSUE TITLE
plist Serialize/Deserialize

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Lab/BP2016H1#12]
In order to write out kerning data, we will need a plist writer. Furthermore, the current plist reader only supports dict elements as root, whereas the spec allows arbitrary elements. (e.g. layercontents.plist is an array)

**Comment by krono** [comment]
Here's the DTD:
https://www.apple.com/DTDs/PropertyList-1.0.dtd

**Comment by krono** [comment]
Also, here's a more complete XML parser:

```Smalltalk
MCHttpRepository
	location: 'http://www.smalltalkhub.com/mc/PharoExtras/XMLParser/main'
	user: ''
	password: ''
```

**Comment by justus-hildebrand** [comment]
deserializing plists is working so far, next up: serializing.
