### ISSUE TITLE
Fix Squeak Promises

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Lab/BP2016H1#148]
Squeak promises are swallowing errors all over the place. We need to fix them to adhere to the promises spec. https://promisesaplus.com/

**Comment by krono** [comment]
Well, they _should_ make sense. Whether they adhere to that JavaScript-specific specification should be discussed on a later date :)

**Comment by tom95** [comment]
Quote from the Promise's class description ;)
> I also implement the Promises/A+ Javascript specification. This allows you to chain my instances to perform arbitrarily complex asynchronous tasks with error handling baked in.

Promise is a very well-defined term for me and I think re-using this term for a class should give me the same behavior I expect from the de-facto standard definition of it. The current implementation is severely broken when it comes to chaining promises. Its behavior is not documented, forcing you to dig through the code once (if) you realize that this particular Promise is in fact not behaving as any other Promise you used before.
