### ISSUE TITLE
Server Deployment

### ISSUE THREAD

**Issue by corinnaj** [HPI-SWA-Lab/BP2016H1#169]
- [x] get a server

set up stuff on server:
- [x] Clone Repository
- [x] Install Pango
- [x] Install pip3 and python3
- [x] run pip3 install -r requirements.txt
- [x] Run sudo apt install libfreetype6-dev libharfbuzz-dev
- [x] Run python3 setup.py install --user

 make Production Mode
- [x] put the server in the autostart
- [x] restart server after crash
- [x] commands for (re)booting/shutting down the server
- [x] logs
- [x] backups for the db
- [x] change database path
- [x] change database type (Postgres or MySQL probably)
- [x] migrations? what happens if we remove/add fields (with default value)?
- [x] documentation

**Comment by tom95** [comment]
Migrations: https://github.com/HPI-SWA-Lab/BP2016H1/issues/188
