### ISSUE TITLE
Page for all threads

### ISSUE THREAD

**Issue by ekrebs5** [HPI-SWA-Lab/BP2016H1#234]
I want a page with all threads, in order to also find closed threads easily

- [x] rename "open discussions" to "discussions"
- [x] checkbox to (not) show closed threads
- [x] only thread or font authors can close threads

**Comment by aloeser** [comment]
We decided to rename the "Open Discussions" Tab on the FontPage, now its simply "Discussions" with a checkbox that allows to also show closed threads

**Comment by aloeser** [comment]
Also, we decided to show the "Close thread" button only to thread starters and font owners
(its working, atm writing tests)
