### ISSUE TITLE
Various Font Design Tools

### ISSUE THREAD

**Issue by marceltaeumel** [HPI-SWA-Lab/BP2016H1#4]
Try out, study, and document the important bits on a Wiki page:

https://glyphsapp.com/
http://www.fontlab.com/
https://fontforge.github.io/
http://doc.robofont.com/
http://trufont.github.io/

http://metapolator.com/
http://glyphrstudio.com/
https://www.prototypo.io/

**Comment by corinnaj** [comment]
Ich habe schon mal eine Seite im Wiki angefangen, in der ich etwas zu FontForge und Trufont geschrieben habe. Ich habe 3 Kategorien verwendet: Usability (wie leicht lässt sich das Tool verwenden), Support (was für Alphabete unterstützt es), und General (auf welchen Betiebssystemen läuft es, was kostet es, etc.)
